# This is a basic workflow to help you get started with Actions

name: Build NTTB Tournament Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    environment: nttb-ranglijsten
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - run: npm ci
      - run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: nttb-tournament-web
          path: public/*
      - run: node ./scripts/correction-for-nttb-ranglijsten.js
      - uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: nttb-ranglijsten.nl
          protocol: ftps
          username: ${{secrets.SFTP_USERNAME}}
          password: ${{secrets.SFTP_PASSWORD}}
          local-dir: public/
          server-dir: /var/www/ranglijsten/clubtoernooi/
